baseURL = "https://wibur.github.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of Vancer"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
publishdir = "./docs"

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Vancer's Blog"
author = "Vancer"
description = "Call me Vancer"
profilePicture = "images/v.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"]
images = ["images/preview.png"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://de.linkedin.com/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/lxndrblz/anatole/"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:yuchihchen159951@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Coding"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

[[menu.main]]
  name = "LeetCode"
  weight = 300
  identifier = "practice"
  url = "/leetcode/"

  [[menu.main]]
  name = "About"
  weight = 400
  identifier = "about"
  url = "/about/"